# netlify.toml
[build]
  command = "next build && next export"
  publish = "out"
  [[redirects]]
  from = "*"
  to ="/"
  status = 200
  [build.environment]
    NODE_OPTIONS = "--max_old_space_size=4096"