export const LOADING = 'LOADING';
export const SUCCESS = 'SUCCESS';
export const ERROR = 'ERROR';
export const RESET = 'RESET';

export const GET_ORDERS = "GET_ORDERS";
export const GET_ORDERS_SUCCESS = "GET_ORDERS_SUCCESS";
export const GET_ORDERS_ERROR = "GET_ORDERS_ERROR";

export const GET_ORDER = "GET_ORDER";
export const GET_ORDER_SUCCESS = "GET_ORDER_SUCCESS";
export const GET_ORDER_ERROR = "GET_ORDER_ERROR";

export const CREATE_ORDERS = "CREATE_ORDERS";
export const CREATE_ORDERS_SUCCESS = "CREATE_ORDERS_SUCCESS";
export const CREATE_ORDERS_ERROR = "CREATE_ORDERS_ERROR";

export const GET_LANGUAGES = "GET_LANGUAGES"
export const LANGUAGE_SUCCESS = "LANGUAGE_SUCCESS";
export const LANGUAGE_ERROR = "LANGUAGE_ERROR";

export const GET_LEVELS = "GET_LEVELS";
export const LEVEL_SUCCESS = "LEVEL_SUCCESS";
export const LEVEL_ERROR = "LEVEL_ERROR";

export const GET_PAGES= "GET_PAGES";
export const PAGE_SUCCESS = "PAGE_SUCCESS";
export const PAGE_ERROR = "PAGE_ERROR";

export const GET_SERVICES= "GET_SERVICES";
export const SERVICE_SUCCESS = "SERVICE_SUCCESS";
export const SERVICE_ERROR = "SERVICE_ERROR";

export const GET_SOURCES= "GET_SOURCES";
export const SOURCE_SUCCESS = "SOURCE_SUCCESS";
export const SOURCE_ERROR = "SOURCE_ERROR";

export const GET_SPACING= "GET_SPACING";
export const SPACING_SUCCESS = "SPACING_SUCCESS";
export const SPACING_ERROR = "SPACING_ERROR";

export const GET_STYLES= "GET_STYLES";
export const STYLE_SUCCESS = "STYLE_SUCCESS";
export const STYLE_ERROR = "STYLE_ERROR";

export const GET_SUBJECTS= "GET_SUBJECTS";
export const GET_SUBJECT_SUCCESS = "GET_SUBJECT_SUCCESS";
export const GET_SUBJECT_ERROR = "GET_SUBJECT_ERROR";

export const GET_TYPES= "GET_TYPES";
export const GET_TYPE_SUCCESS = "GET_TYPE_SUCCESS";
export const GET_TYPE_ERROR = "GET_TYPE_ERROR";

export const GET_URGENCY= "GET_URGENCY";
export const GET_URGENCY_SUCCESS = "GET_URGENCY_SUCCESS";
export const GET_URGENCY_ERROR = "GET_URGENCY_ERROR";

export const MAKE_PAYMENT= "MAKE_PAYMENT";
export const MAKE_PAYMENT_SUCCESS = "MAKE_PAYMENT_SUCCESS";
export const MAKE_PAYMENT_ERROR = "MAKE_PAYMENT_ERROR";

export const EXECUTE_PAYMENT= "EXECUTE_PAYMENT";
export const EXECUTE_PAYMENT_SUCCESS = "EXECUTE_PAYMENT_SUCCESS";
export const EXECUTE_PAYMENT_ERROR = "EXECUTE_PAYMENT_ERROR";