export const LOADING = 'LOADING';
export const SUCCESS = 'SUCCESS';
export const ERROR = 'ERROR';
export const RESET = 'RESET';

export const GET_ORDERS = "GET_ORDERS";
export const GET_ORDERS_SUCCESS = "GET_ORDERS_SUCCESS";
export const GET_ORDERS_ERROR = "GET_ORDERS_ERROR";

export const GET_COMPLETED_ORDERS = "GET_COMPLETED_ORDERS";
export const GET_COMPLETED_ORDERS_SUCCESS = "GET_COMPLETED_ORDERS_SUCCESS";
export const GET_COMPLETED_ORDERS_ERROR = "GET_COMPLETED_ORDERS_ERROR";

export const GET_APPROVED_ORDERS = "GET_APPROVED_ORDERS";
export const GET_APPROVED_ORDERS_SUCCESS = "GET_APPROVED_ORDERS_SUCCESS";
export const GET_APPROVED_ORDERS_ERROR = "GET_APPROVED_ORDERS_ERROR";

export const GET_ACTIVE_ORDERS = "GET_ACTIVE_ORDERS";
export const GET_ACTIVE_ORDERS_SUCCESS = "GET_ACTIVE_ORDERS_SUCCESS";
export const GET_ACTIVE_ORDERS_ERROR = "GET_ACTIVE_ORDERS_ERROR";

export const GET_REJECTED_ORDERS = "GET_REJECTED_ORDERS";
export const GET_REJECTED_ORDERS_SUCCESS = "GET_REJECTED_ORDERS_SUCCESS";
export const GET_REJECTED_ORDERS_ERROR = "GET_REJECTED_ORDERS_ERROR";

export const GET_CANCELLED_ORDERS = "GET_CANCELLED_ORDERS";
export const GET_CANCELLED_ORDERS_SUCCESS = "GET_CANCELLED_ORDERS_SUCCESS";
export const GET_CANCELLED_ORDERS_ERROR = "GET_CANCELLED_ORDERS_ERROR";

export const GET_PENDING_ORDERS = "GET_PENDING_ORDERS";
export const GET_PENDING_ORDERS_SUCCESS = "GET_PENDING_ORDERS_SUCCESS";
export const GET_PENDING_ORDERS_ERROR = "GET_PENDING_ORDERS_ERROR";

export const GET_WAITING_ASSIGN_ORDERS = "GET_WAITING_ASSIGN_ORDERS";
export const GET_WAITING_ASSIGN_ORDERS_SUCCESS = "GET_WAITING_ASSIGN_ORDERS_SUCCESS";
export const GET_WAITING_ASSIGN_ORDERS_ERROR = "GET_WAITING_ASSIGN_ORDERS_ERROR";

export const GET_ORDER = "GET_ORDER";
export const GET_ORDER_SUCCESS = "GET_ORDER_SUCCESS";
export const GET_ORDER_ERROR = "GET_ORDER_ERROR";

export const CREATE_ORDER = "CREATE_ORDER";
export const CREATE_ORDER_SUCCESS = "CREATE_ORDER_SUCCESS";
export const CREATE_ORDER_ERROR = "CREATE_ORDER_ERROR";

export const UPDATE_ORDER = "UPDATE_ORDER";
export const UPDATE_ORDER_SUCCESS = "UPDATE_ORDER_SUCCESS";
export const UPDATE_ORDER_ERROR = "UPDATE_ORDER_ERROR";

export const DELETE_ORDER= "DELETE_ORDER";
export const DELETE_ORDER_SUCCESS = "DELETE_ORDER_SUCCESS";
export const DELETE_ORDER_ERROR = "DELETE_ORDER_ERROR";

export const GET_LANGUAGES = "GET_LANGUAGES"
export const LANGUAGE_SUCCESS = "LANGUAGE_SUCCESS";
export const LANGUAGE_ERROR = "LANGUAGE_ERROR";

export const GET_LEVELS = "GET_LEVELS";
export const LEVEL_SUCCESS = "LEVEL_SUCCESS";
export const LEVEL_ERROR = "LEVEL_ERROR";

export const GET_PAGES= "GET_PAGES";
export const PAGE_SUCCESS = "PAGE_SUCCESS";
export const PAGE_ERROR = "PAGE_ERROR";

export const GET_SERVICES= "GET_SERVICES";
export const SERVICE_SUCCESS = "SERVICE_SUCCESS";
export const SERVICE_ERROR = "SERVICE_ERROR";

export const GET_SOURCES= "GET_SOURCES";
export const SOURCE_SUCCESS = "SOURCE_SUCCESS";
export const SOURCE_ERROR = "SOURCE_ERROR";

export const GET_SPACING= "GET_SPACING";
export const SPACING_SUCCESS = "SPACING_SUCCESS";
export const SPACING_ERROR = "SPACING_ERROR";

export const GET_STYLES= "GET_STYLES";
export const STYLE_SUCCESS = "STYLE_SUCCESS";
export const STYLE_ERROR = "STYLE_ERROR";

export const GET_SUBJECTS= "GET_SUBJECTS";
export const GET_SUBJECT_SUCCESS = "GET_SUBJECT_SUCCESS";
export const GET_SUBJECT_ERROR = "GET_SUBJECT_ERROR";

export const GET_TYPES= "GET_TYPES";
export const GET_TYPE_SUCCESS = "GET_TYPE_SUCCESS";
export const GET_TYPE_ERROR = "GET_TYPE_ERROR";

export const GET_URGENCY= "GET_URGENCY";
export const GET_URGENCY_SUCCESS = "GET_URGENCY_SUCCESS";
export const GET_URGENCY_ERROR = "GET_URGENCY_ERROR";

export const GET_USER_COUNT_SUMMARY= "GET_USER_COUNT_SUMMARY";
export const GET_USER_COUNT_SUMMARY_SUCCESS = "GET_USER_COUNT_SUMMARY_SUCCESS";
export const GET_USER_COUNT_SUMMARY_ERROR = "GET_USER_COUNT_SUMMARY_ERROR";

export const GET_USER_WALLET_SUMMARY= "GET_USER_WALLET_SUMMARY";
export const GET_USER_WALLET_SUMMARY_SUCCESS = "GET_USER_WALLET_SUMMARY_SUCCESS";
export const GET_USER_WALLET_SUMMARY_ERROR = "GET_USER_WALLET_SUMMARY_ERROR";

export const MAKE_PAYMENT= "MAKE_PAYMENT";
export const MAKE_PAYMENT_SUCCESS = "MAKE_PAYMENT_SUCCESS";
export const MAKE_PAYMENT_ERROR = "MAKE_PAYMENT_ERROR";

export const EXECUTE_PAYMENT= "EXECUTE_PAYMENT";
export const EXECUTE_PAYMENT_SUCCESS = "EXECUTE_PAYMENT_SUCCESS";
export const EXECUTE_PAYMENT_ERROR = "EXECUTE_PAYMENT_ERROR";

export const FILTER_WALLET_TRANSACTIONS= "FILTER_WALLET_TRANSACTIONS";
export const FILTER_WALLET_TRANSACTIONS_SUCCESS = "FILTER_WALLET_TRANSACTIONS_SUCCESS";
export const FILTER_WALLET_TRANSACTIONS_ERROR = "FILTER_WALLET_TRANSACTIONS_ERROR";

export const FILE_UPLOADING = "FILE_UPLOADING";
export const FILE_UPLOADING_SUCCESS = "FILE_UPLOADING_SUCCESS";
export const FILE_UPLOADING_ERROR = "FILE_UPLOADING_ERROR";

export const ORDER_FILES = "ORDER_FILES";
export const ORDER_FILES_SUCCESS = "ORDER_FILES_SUCCESS";
export const ORDER_FILES_ERROR = "ORDER_FILES_ERROR";


export const FILTER_USER_RATINGS = "FILTER_USER_RATINGS";
export const FILTER_USER_RATINGS_SUCCESS = "FILTER_USER_RATINGS_SUCCESS";
export const FILTER_USER_RATINGS_ERROR = "FILTER_USER_RATINGS_ERROR";

export const CREATE_USER_RATINGS = "CREATE_USER_RATINGS";
export const CREATE_USER_RATINGS_SUCCESS = "CREATE_USER_RATINGS_SUCCESS";
export const CREATE_USER_RATINGS_ERROR = "CREATE_USER_RATINGS_ERROR";

export const CREATE_MESSAGE = "CREATE_MESSAGE";
export const CREATE_MESSAGE_SUCCESS = "CREATE_MESSAGE_SUCCESS";
export const CREATE_MESSAGE_ERROR = "CREATE_MESSAGE_ERROR";

export const LIST_MESSAGES= "LIST_MESSAGES";
export const LIST_MESSAGES_SUCCESS = "LIST_MESSAGES_SUCCESS";
export const LIST_MESSAGES_ERROR = "LIST_MESSAGES_ERROR";